### ISSUE TITLE
.vim/rc/dein.toml内のcoc.nvimに関する設定表記が誤っているかもしれません

### ISSUE THREAD

**Issue by HDisc** [craftzdog/dotfiles-public#1]
.vim/rc/dein.toml内のcoc.nvimの設定表記が誤っているかもと思いましたのでご確認ください。
当該ファイルの74行目
```
merge = 0
```
と書かれている箇所は
```
merged = 0
```
と書かれるべきかもしれません。
変更後↓
```toml
[[plugins]]
repo = "neoclide/coc.nvim"
merge = 0
rev = "release"
hook_add = """
source ~/.config/nvim/plugins/coc.rc.vim
"""
```

元のドキュメントにも関連がありそうな注意書きがありましたので載せておきます。
**Note: When 'merged': 0 not present, coc.nvim will be unable to start.**
[neoclide/coc.nvim](https://github.com/neoclide/coc.nvim/wiki/Install-coc.nvim#using-deinvim)

(※以下issueとは関係ないですがお伝えさせてください。)
YouTube拝見させていただき、vim沼に飛び込むべく参考にさせていただきました！
まだvim歴は浅く、vimmerの知人が1人しかいない自分がvimmerとして独り立ちできるきっかけとなった動画でした。
VSCodeでvimのキーバインドは学んだものの、本物のvimmerとしてのステップに進めずにいたときに拝見しました。
動画の編集力も上乗せされて、まず最初に「かっこいい！」その次に「こうなりたい！」と思いました。
その日からiterm2, tmux, neovim, など諸々を揃え、動画やネットの記事を参考に設定を進めています。
今回のissueの内容もそのときに見つけたものです。正直ご報告するほどのことでもないかと思いましたが、私と似たようなvimmerが少しでも躓かないようにと思いお伝えさせていただきました。
いままでGithubでissueを立てたことがなく、もし見づらかったら申し訳ありません。
